#! /bin/bash
### BEGIN INIT INFO
# Provides:          snapexit
# Required-Start:   
# Required-Stop:    $local_fs $remote_fs alsa-utils frisbee
# Default-Start:    
# Default-Stop:      0 1 6
# Short-Description: Save on exit
# Description: Save on exit when shutdown from console
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions


case "$1" in
  start)
# no-opt
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	if [ -f /mnt/live/tmp/modules ]; then
	#clear
	exec /usr/local/bin/snap-ex </dev/console >/dev/console 2>&1
	fi
        ;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

:
